DetailsPage
Basmae/OnlineShoppingAngular pull request #3
Opened 2019-07-24 09:22 UTC by Basmae

2019-07-24 10:28 UTC, dosama1integrant requested changes

2019-07-24 10:28 UTC, dosama1integrant commented on app/components/HomeComponent/home.html
> +                <a href="#/details/{{product.id}}">
recommended to use ng-href instead href 
Please apply to all href usages in the application

2019-07-24 10:28 UTC, dosama1integrant commented on app/shared/localStorageService.js
> +        GetUserName: function () {
we can simplify the logic here instead of generating method for each Key :
1- To set Local storage data generate method to take key and value to set the value we want in local storage service.
2- To get data from local storage we can generate method to take the key as parameter and return the stored value

2019-07-24 10:28 UTC, dosama1integrant commented on app/shared/navBar/navBar.html
> +            <img src="../../../assets/img/avatar.png" class="rounded-circle z-depth-0" alt="avatar image" height="35">
recommended to use ng-src instead of src ..
please apply to all image references in the application

2019-07-24 10:28 UTC, dosama1integrant commented on assets/js/controllers/ProductController.js
> +        $scope.userName=localStorageService.GetUserName();
👍

2019-07-24 14:56 UTC, Basmae commented on app/components/HomeComponent/home.html
> +                <a href="#/details/{{product.id}}">
Done

2019-07-24 14:56 UTC, Basmae commented on app/shared/localStorageService.js
> +        GetUserName: function () {
Done

2019-07-24 14:57 UTC, Basmae commented on app/shared/navBar/navBar.html
> +            <img src="../../../assets/img/avatar.png" class="rounded-circle z-depth-0" alt="avatar image" height="35">
Done

2019-07-24 18:43 UTC, dosama1integrant requested changes

2019-07-24 18:43 UTC, dosama1integrant commented on app/app.config.js
> +OnlineShoppingApp.constant('API',{
https://localhost:44367/ is always common in your URL config you can define it once in separate variable and concatenate it to the service name. so that when we need to change the api url to change it once in this variable and not to change it  for each service.

2019-07-24 18:43 UTC, dosama1integrant commented on app/components/DetailsComponent/details.html
> +            <a class="carousel-control-prev" ng-href="" role="button" data-slide="prev" ng-click="carouselPrev()">
We can delete empty ng-href if you are going to handle ng-click on it
Apply it to each similar case

2019-07-24 18:43 UTC, dosama1integrant commented on app/shared/localStorageService.js
> +        Set:function(Key , value)
Perfect :)

2019-07-25 09:19 UTC, Basmae commented on app/shared/localStorageService.js
> +        Set:function(Key , value)
Thank you

2019-07-25 10:50 UTC, merged